In [1]:
import pandas as pd
pd.set_option('display.max_colwidth',1)
import Opuiori

## Sample Dataset

In [2]:
data = pd.read_csv("groceries.csv",error_bad_lines=False,header=None,warn_bad_lines=False);
records = []
for i in range((len(data))):
    records.append([str(data.values[i,j]) for j in range(0, data.shape[1])])

In [3]:
frequent_itemsets,rules=Opuiori.apriori(records,min_sup=0.003,min_conf=0.5)

In [4]:
frequent_itemsets

     index             Frequent Itemsets   Support
0    0      (citrus fruit,)               0.034065
1    1      (semi-finished bread,)        0.008189
2    2      (margarine,)                  0.021946
3    3      (tropical fruit,)             0.039797
4    4      (yogurt,)                     0.062889
..  ..            ...                          ...
184  184    (bottled water, white wine)   0.003439
185  185    (canned beer, shopping bags)  0.004422
186  186    (bottled beer, sausage)       0.003112
187  187    (bottled beer, liquor)        0.005896
188  188    (soda, sausage, rolls/buns)   0.003439

[189 rows x 3 columns]

In [5]:
rules

   index      antecedents      consequents  Confidence
0  0      (liquor,)        (bottled beer,)  0.5625
1  1      (soda, sausage)  (rolls/buns,)    0.5000

## Own Dataset

In [6]:
df=pd.read_csv("MLData.csv")
columns=["Timestamp","Level","Class","Scale","Gender","Age","Residence","RelationshipStatus","FinanceState","CopeWithInstitute","RelationWithFamily","Pressure","AcademicResult","LivingPlace","SupportedBy","SocialMediaIn6","InferiorityComplex","MealSatisfaction","Health","OtherPositiveActivity","SleepTime"]
df.columns=columns
df=df.drop(['Scale','Timestamp'],axis=1)
def NameCopeWithInstitute(x):
    if x==1:
        return "Definitely Not Successful"
    elif x==2:
        return "Probably Not Successful"
    elif x==3:
        return "Possibly Successful"
    elif x==4:
        return "Probably Successful"
    elif x==5:
        return "Definitely Successful"
    

df['CopeWithInstitute']=df['CopeWithInstitute'].apply(NameCopeWithInstitute)
df['FinanceState']=df['FinanceState'].apply(lambda x: 'Good Finance' if x=="Yes" else "Bad Finance")
df['RelationWithFamily']=df['RelationWithFamily'].apply(lambda x: x+" Relation With Family")
df['Pressure']=df['Pressure'].apply(lambda x: x+" Pressure")
df['AcademicResult']=df['AcademicResult'].apply(lambda x: "Result "+x)
df['LivingPlace']=df['LivingPlace'].apply(lambda x: "Living Place "+x)
df['SupportedBy']=df['SupportedBy'].apply(lambda x: "Supported By "+x)
df['SocialMediaIn6']=df['SocialMediaIn6'].apply(lambda x: x+" SocialMediaIn6")
df['InferiorityComplex']=df['InferiorityComplex'].apply(lambda x: x+" InferiorityComplex")
df['MealSatisfaction']=df['MealSatisfaction'].apply(lambda x: x+" MealSatisfaction")
df['Health']=df['Health'].apply(lambda x: x+" HealthProblem")
df['OtherPositiveActivity']=df['OtherPositiveActivity'].apply(lambda x: x+" OtherPositiveActivity")
df['SleepTime']=df['SleepTime'].apply(lambda x: "SleepTime "+str(x))
records = []
for i in range((len(df))):
    records.append([str(df.values[i,j]) for j in range(0, df.shape[1])])

In [7]:
frequent_itemsets,rules=Opuiori.apriori(records,min_sup=0.8,min_conf=0.5)

In [8]:
frequent_itemsets

,index,Frequent Itemsets,Support
0,0,"(Male,)",1.000000
1,1,"(Single,)",0.803922
2,2,"(Normal Relation With Family,)",1.000000
3,3,"(No Pressure,)",0.823529
4,4,"(Supported By No one,)",0.941176
...,...,...,...
82,89,"(No HealthProblem, Yes InferiorityComplex, Normal Relation With Family, Male, Supported By No one)",0.882353
83,90,"(No HealthProblem, Yes InferiorityComplex, Normal Relation With Family, Male, Yes SocialMediaIn6, Supported By No one)",0.843137
84,93,"(No HealthProblem, Yes InferiorityComplex, Normal Relation With Family, Male, Yes SocialMediaIn6)",0.843137
85,97,"(No HealthProblem, Yes InferiorityComplex, Male, Yes SocialMediaIn6, Supported By No one)",0.843137
86,103,"(No HealthProblem, Yes InferiorityComplex, Normal Relation With Family, Yes SocialMediaIn6, Supported By No one)",0.843137

In [9]:
rules.reset_index()

,level_0,index,antecedents,consequents,Confidence
0,0,0,"(Male,)","(Single,)",0.803922
1,1,1,"(Single,)","(Male,)",1.000000
2,2,2,"(Male,)","(Normal Relation With Family,)",1.000000
3,3,3,"(Normal Relation With Family,)","(Male,)",1.000000
4,4,4,"(Male,)","(No Pressure,)",0.823529
...,...,...,...,...,...
765,765,1003,"(No HealthProblem, Normal Relation With Family)","(Yes InferiorityComplex, Yes SocialMediaIn6, Supported By No one)",0.843137
766,766,1004,"(Normal Relation With Family,)","(No HealthProblem, Yes InferiorityComplex, Yes SocialMediaIn6, Supported By No one)",0.843137
767,767,1005,"(No HealthProblem, Yes InferiorityComplex)","(Normal Relation With Family, Yes SocialMediaIn6, Supported By No one)",0.955556
768,768,1006,"(Yes InferiorityComplex,)","(No HealthProblem, Normal Relation With Family, Yes SocialMediaIn6, Supported By No one)",0.955556
769,769,1007,"(No HealthProblem,)","(Yes InferiorityComplex, Normal Relation With Family, Yes SocialMediaIn6, Supported By No one)",0.843137